window.SITE = {
  home: "images/home.jpg",
  email: "worktheeryder@gmail.com",
  instagram: "@theeryder",
  welcome: "WELCOME to THEERYDER",

  projects: [
    {
      id: "office", no: "01", title: "OFFICE",
      blurb: "The \"OFFICE\" is a bold reimagination of corporate chic, where professionalism meets allure and confidence takes center stage. Drawing inspiration from films like The Devil Wears Prada and Secretary, this photoshoot delves into the magnetic world of ambition, power dynamics, and sophistication. The contrasting atmosphere amplifies Nata Galagan's striking collection and styling by Yaryna Lahoda.",
      credits: [
        "Models: Ivana Benadová @ivana.benadova · Michelle Paniková @michellepanikova_ represented by Exit Model Management @exitmodelmanagement",
        "Fashion Designer: Nata Galagan @galagan.brand",
        "Styling: Yaryna Lahoda @yaryna_lahoda",
        "Stage Assistants: Ilia and @holy__satan",
      ],
      images: [
        { src: "images/office/01.jpg", span: 2 },
        { src: "images/office/02.jpg", span: 1 },
        { src: "images/office/03.jpg", span: 1 },
        { src: "images/office/04.jpg", span: 2 },
        { src: "images/office/05.jpg", span: 2 },
        { src: "images/office/06.jpg", span: 1 },
        { src: "images/office/07.jpg", span: 1 },
        { src: "images/office/08.jpg", span: 2 },
        { src: "images/office/09.jpg", span: 2 },
        { src: "images/office/10.jpg", span: 2 },
        { src: "images/office/11.jpg", span: 1 },
        { src: "images/office/12.jpg", span: 1 },
      ],
    },
    {
      id: "spomyn", no: "02", title: "SPOMYN",
      blurb: "The \u201cSPOMYN\u201d Collection is a celebration of tradition and modernity, seamlessly blending the rich tapestry of Ukrainian culture with cutting-edge design. Yaryna Lahoda's vision is embodied in every stitch, showcasing a deep connection to her heritage while embracing sustainable and eco-friendly practices through the use of hemp fabric. Capturing the essence of this unique collection is the stunning model, Rita Markytan, from the renowned Look Models Int.",
      credits: [
        "Fashion Designer: Yaryna Lahoda @yaryna_lahoda",
        "Model: Rita Markytan @ Look Models Int.",
      ],
      images: [
        { src: "images/spomyn/01.jpg", span: 2 },
        { src: "images/spomyn/02.jpg", span: 1 },
        { src: "images/spomyn/03.jpg", span: 1 },
        { src: "images/spomyn/04.jpg", span: 2 },
        { src: "images/spomyn/05.jpg", span: 2 },
        { src: "images/spomyn/06.jpg", span: 1 },
        { src: "images/spomyn/07.jpg", span: 1 },
        { src: "images/spomyn/08.jpg", span: 2 },
        { src: "images/spomyn/09.jpg", span: 2 },
        { src: "images/spomyn/10.jpg", span: 2 },
        { src: "images/spomyn/11.jpg", span: 2 },
        { src: "images/spomyn/12.jpg", span: 2 },
        { src: "images/spomyn/13.jpg", span: 1 },
        { src: "images/spomyn/14.jpg", span: 1 },
        { src: "images/spomyn/15.jpg", span: 2 },
        { src: "images/spomyn/16.jpg", span: 2 },
        { src: "images/spomyn/17.jpg", span: 2 },
        { src: "images/spomyn/18.jpg", span: 2 },
        { src: "images/spomyn/19.jpg", span: 2 },
        { src: "images/spomyn/20.jpg", span: 2 },
      ],
    },
    {
      id: "schiz-drama", no: "03", title: "SCHIZ. DRAMA",
      blurb: "The \"Schiz. Drama\" is a staged photography experiment, a journey into the depths of VVAIN's artistic psyche. The series shows his amazing change in a variety of settings, from a rustic western bar to the modern air of an office complex. Each shot constitutes a chapter in the dramatic narrative, capturing VVAIN's adaptability and transcendence. It's a visual symphony that reflects the breadth and complexity of his next album.",
      credits: [
        "Producer: VVAIN @we_live_invain · Production Manager: @jana_es_",
        "Gaffer: @schafer.leon",
        "Makeup Artists: Sophia Gunev @sophia.gunev / Jasmin @jasminsbeautea",
        "Talents: @sasukekilledsonic / @idamanduh / @maddie__mad / @new_moonjones / @filip_fecko",
        "Set Assistant: Elli @__ellii",
        "Location: Michalska Cocktail Room @michalskacocktailroom",
      ],
      images: [
        { src: "images/schiz/01.jpg", span: 1 },
        { src: "images/schiz/02.jpg", span: 1 },
        { src: "images/schiz/03.jpg", span: 2 },
        { src: "images/schiz/04.jpg", span: 1 },
        { src: "images/schiz/05.jpg", span: 1 },
        { src: "images/schiz/06.jpg", span: 1 },
        { src: "images/schiz/07.jpg", span: 1 },
        { src: "images/schiz/08.jpg", span: 1 },
        { src: "images/schiz/09.jpg", span: 1 },
        { src: "images/schiz/10.jpg", span: 2 },
        { src: "images/schiz/11.jpg", span: 2 },
        { src: "images/schiz/12.jpg", span: 1 },
        { src: "images/schiz/13.jpg", span: 1 },
        { src: "images/schiz/14.jpg", span: 2 },
        { src: "images/schiz/15.jpg", span: 2 },
        { src: "images/schiz/16.jpg", span: 2 },
        { src: "images/schiz/17.jpg", span: 2 },
        { src: "images/schiz/18.jpg", span: 2 },
        { src: "images/schiz/19.jpg", span: 2 },
        { src: "images/schiz/20.jpg", span: 2 },
        { src: "images/schiz/21.jpg", span: 2 },
        { src: "images/schiz/22.jpg", span: 2 },
        { src: "images/schiz/23.jpg", span: 2 },
        { src: "images/schiz/24.jpg", span: 2 },
        { src: "images/schiz/25.jpg", span: 2 },
      ],
    },
    {
      id: "mimicry", no: "04", title: "MIMICRY",
      blurb: "Dive into a world of colorful expression with our exclusive photograph featuring a rising Slovak fashion designer - Kristian Stanko. This young, innovative apparel designer is creating waves with their wonderfully colored and saturated outfits, which we had the honor of featuring in the renowned October issue of ESTIMAG.",
      credits: [
        "Model: Jana Stankovi\u010dov\u00e1 @jana_es_",
        "Fashion Designer: Kristian Stanko @s_kikino",
      ],
      images: [
        { src: "images/mimicry/01.jpg", span: 2 },
        { src: "images/mimicry/02.jpg", span: 1 },
        { src: "images/mimicry/03.jpg", span: 1 },
        { src: "images/mimicry/04.jpg", span: 2 },
        { src: "images/mimicry/05.jpg", span: 2 },
        { src: "images/mimicry/06.jpg", span: 2 },
        { src: "images/mimicry/07.jpg", span: 1 },
        { src: "images/mimicry/08.jpg", span: 1 },
        { src: "images/mimicry/09.jpg", span: 2 },
      ],
    },
    {
      id: "liminal-space", no: "05", title: "LIMINAL SPACE",
      blurb: "",
      credits: [],
      images: [
       
        { vimeo: "1199567681" },
        // ▲▲▲  end video  ▲▲▲
        { src: "images/liminal/01.jpg", span: 2 },
        { src: "images/liminal/02.jpg", span: 2 },
        { src: "images/liminal/03.jpg", span: 1 },
        { src: "images/liminal/04.jpg", span: 1 },
        { src: "images/liminal/05.jpg", span: 1 },
        { src: "images/liminal/06.jpg", span: 1 },
        { src: "images/liminal/07.jpg", span: 2 },
        { src: "images/liminal/08.jpg", span: 1 },
        { src: "images/liminal/09.jpg", span: 1 },
        { src: "images/liminal/10.jpg", span: 2 },
        { src: "images/liminal/11.jpg", span: 1 },
        { src: "images/liminal/12.jpg", span: 1 },
        { src: "images/liminal/13.jpg", span: 2 },
      ],
    },
    {
      id: "optical-error", no: "06", title: "OPTICAL ERROR",
      blurb: "My project\u2019s theme is intended to lead to an exploration of the perspective of imaging through an analysis of the physical properties of light, optical errors and illusions as issues of reality simulation. The distortion expressed through the errors of representation becomes the key to unravelling a type of contradiction between experience and memory. At the same time, the possibilities of creating visual artefacts as images of a non-existent original will be explored in the context of reading an elusive reality. The starting point of the topic is the re-evaluation of imaging based on creative experimentation with optical errors such as aberration, coma, astigmatism, distortion and after-image.",
      credits: [],
      images: [
        { src: "images/optical/01.jpg", span: 2 },
        { src: "images/optical/02.jpg", span: 2 },
        { src: "images/optical/03.jpg", span: 2 },
        { src: "images/optical/04.jpg", span: 1 },
        { src: "images/optical/05.jpg", span: 1 },
        { src: "images/optical/06.jpg", span: 2 },
        { src: "images/optical/07.jpg", span: 1 },
        { src: "images/optical/08.jpg", span: 1 },
        { src: "images/optical/09.jpg", span: 2 },
        { src: "images/optical/10.jpg", span: 1 },
        { src: "images/optical/11.jpg", span: 1 },
        { src: "images/optical/12.jpg", span: 2 },
        { src: "images/optical/13.jpg", span: 1 },
        { src: "images/optical/14.jpg", span: 1 },
        { src: "images/optical/15.jpg", span: 2 },
        { src: "images/optical/16.jpg", span: 1 },
        { src: "images/optical/17.jpg", span: 1 },
        { src: "images/optical/18.jpg", span: 2 },
        { src: "images/optical/19.jpg", span: 2 },
        { src: "images/optical/20.jpg", span: 2 },
        { src: "images/optical/21.jpg", span: 1 },
        { src: "images/optical/22.jpg", span: 1 },
        { src: "images/optical/23.jpg", span: 1 },
        { src: "images/optical/24.jpg", span: 1 },
      ],
    },
    {
      id: "archive", no: "07", title: "ARCHIVE",
      blurb: "",
      credits: [
        "Models: Jana Stankovi\u010dov\u00e1 @jana_es_ / Alina Shkvarchuk @sh.alinaa / Daria @composexigirll / Arina @oveisrrreal / Jane Crank @janecrank / Savelii Kuzniatsou @sava_savva / Sandy Kirik @sandy__kirik / SARA @RELIKVIA_ / SOPHIa @mazgutova.s",
        "Fashion Designers: Lucia Villarova @cija_villar / Alina Shkvarchuk @sh.alinaa / @laurrrie_ / YORA @_____yora / BLESSURE @blessure2020 / NUAGES",
      ],
      images: [
        { src: "images/archive/01.jpg", span: 2 },
        { src: "images/archive/02.jpg", span: 1 },
        { src: "images/archive/03.jpg", span: 1 },
        { src: "images/archive/04.jpg", span: 2 },
        { src: "images/archive/05.jpg", span: 2 },
        { src: "images/archive/06.jpg", span: 2 },
        { src: "images/archive/07.jpg", span: 2 },
        { src: "images/archive/08.jpg", span: 2 },
        { src: "images/archive/09.jpg", span: 2 },
        { src: "images/archive/10.jpg", span: 2 },
        { src: "images/archive/11.jpg", span: 2 },
        { src: "images/archive/12.jpg", span: 2 },
        { src: "images/archive/13.jpg", span: 2 },
        { src: "images/archive/14.jpg", span: 2 },
        { src: "images/archive/15.jpg", span: 2 },
        { src: "images/archive/16.jpg", span: 2 },
        { src: "images/archive/17.jpg", span: 1 },
        { src: "images/archive/18.jpg", span: 1 },
        { src: "images/archive/19.jpg", span: 2 },
        { src: "images/archive/20.jpg", span: 1 },
        { src: "images/archive/21.jpg", span: 1 },
        { src: "images/archive/22.jpg", span: 2 },
      ],
    },
    {
      id: "picture", no: "08", title: "I AM NOT BUT I AM: THE PICTURE I NEVER WAS",
      blurb: "",
      credits: [
        "Model: @mazgutova.s @wewomenmodels",
        "Creative direction & styling: @theeryder x @blessure2020",
        "Jacket & T-shirt from @blessure2020 collection \u201cONE NIGHT A YEAR AND WHERE THE CYCLE ENDS\u201d",
      ],
      images: [
        { src: "images/picture/01.jpg", span: 2 },
        { src: "images/picture/02.jpg", span: 2 },
        { src: "images/picture/03.jpg", span: 2 },
        { src: "images/picture/04.jpg", span: 1 },
        { src: "images/picture/05.jpg", span: 1 },
        { src: "images/picture/06.jpg", span: 2 },
        { src: "images/picture/07.jpg", span: 2 },
        { src: "images/picture/08.jpg", span: 1 },
        { src: "images/picture/09.jpg", span: 1 },
        { src: "images/picture/10.jpg", span: 1 },
        { src: "images/picture/11.jpg", span: 1 },
        { src: "images/picture/12.jpg", span: 2 },
        { src: "images/picture/13.jpg", span: 1 },
        { src: "images/picture/14.jpg", span: 1 },
        { src: "images/picture/15.jpg", span: 2 },
        { src: "images/picture/16.jpg", span: 2 },
        { src: "images/picture/17.jpg", span: 2 },
        { src: "images/picture/18.jpg", span: 1 },
        { src: "images/picture/19.jpg", span: 1 },
        { src: "images/picture/20.jpg", span: 1 },
        { src: "images/picture/21.jpg", span: 1 },
        { src: "images/picture/22.jpg", span: 2 },
      ],
    },
  ],

  /* ---- INFO page ------------------------------------------------------- */
  info: {
    bio: "Born in Ukraine, Valeriia Eriomenco (Yeromenko), also known as Thee Ryder, is a fashion photographer and visual artist currently based in Bratislava, navigating life in migration. With over five years of practice spanning commercial, editorial, and e-commerce photography, Thee Ryder operates across the full spectrum of image production \u2014 from concept and direction through to retouching and final delivery. Alongside her photographic practice, she extends into 3D/CGI art direction \u2014 developing visual concepts, virtual environments and animatics in Unreal Engine, and collaborating with technical specialists to bring synthetic and real imagery into coherent visual worlds.",
    education: [
      "october 2025 \u2013 february 2026 / Die Akademie der K\u00fcnste Wien \u2014 Visual Arts (Time and Photography)",
      "march 2023 \u2013 september 2023 / Hochschule Bielefeld (HSBI) \u2014 Mixed Media and Videography Techniques",
      "september 2020 \u2013 august 2026 / The Academy of Fine Arts and Design in Bratislava \u2014 Visual Arts (Photography and New Media)",
      "september 2019 \u2013 august 2020 / Catholic University in Ru\u017eomberok \u2014 Mathematics & Programming / Italian Linguistics / Pedagogics",
    ],
    publications: [
      "VOGUE CS \u2014 March 2025",
      "Darkly Art Magazine \u2014 2024",
      "STROFA: nov\u00e1 \u00e9ra po\u00e9zie \u2014 2024",
      "Mob Journal: Portrait Issue \u2014 2024",
      "SAINTEIGHT: No.175 \u2014 September 2024",
      "Vigour: Fashion & Beauty Issue N23 \u2014 2024",
      "BLISS Magazine: April Fashion & Beauty Vol.8 \u2014 2024",
      "17:23 MAG: Special Edition Vol.135 \u2014 2024",
      "ESTIMAG: January Issue N30 \u2014 2024",
      "Feroce: May Volume 6",
      "Volant: #19",
      "ELEGANT: April 2020",
    ],
    fairs: [
      "Paris Photo \u2014 Carte Blanche students (2024)",
      "Photo Vogue \u2014 A Tribute to Ukraine: Chapter IV (2022)",
    ],
    exhibitions: [
      "2026 / Bratislava \u2014 French Institute \u2014 Collective Exhibition \u201cHommage à Monet\u201d",
      "2025 / Prague \u2014 Solarigraphy Meeting 2025 at Planetum",
      "2024\u201325 / Bratislava \u2014 \u201cOrthophoto\u201d at Oldcity Gallery Zichy",
      "2024 / The Hague \u2014 \u201cGhosts of Study Collections\u2019 Past\u201d at KABK",
      "2024 / The Hague \u2014 Cyanotype workshop at KABK x Paris Beaux-Arts",
      "2024 / Bratislava \u2014 \u201cCollective Frameworks\u201d at Kotol\u0148a FAD STU",
      "2023 / Bratislava \u2014 Solo show \u201cAbstract Reality\u201d at Gal\u00e9ria Artot\u00e9ka",
    ],
  },

  /* ---- CONTACT page ---------------------------------------------------- */
  contact: {
    lines: [
      "Available for commissions worldwide",
      "Physically based in Bratislava",
      "Write to worktheeryder@gmail.com",
      "Replies within two (2) working days",
      "Find me on Instagram @theeryder",
    ],
  },
};
